/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prince Giri
 */

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class fees_reciept extends javax.swing.JFrame {

    /**
     * Creates new form fees_reciept
     */
    public fees_reciept() {
        initComponents();
    }
    
    public fees_reciept(String stu_id, String txn_id) {
        initComponents();
        this.stu_id = stu_id;
        this.txn_id = txn_id;
        if(stu_id!=null && txn_id!=null)
        {
            jTextField2.setText(this.stu_id);
            jTextField1.setText(this.txn_id);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DOWNLOAD FEES RECIEPT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter TXN-ID");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Download PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Student-ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private String full_name;
 private String id;
 private String course;
 private String amount;
 private String card_no;
 private String card_holder_name;
 private String expiry_date;
 private String upi_id;
 private String stu_id;
 private String txn_id;
 private String txn_date;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        String get_id=jTextField2.getText();
        String txn_id=jTextField1.getText();
        java.util.Date curr_date=new java.util.Date();
        SimpleDateFormat s1=new SimpleDateFormat("dd/MM/yyyy");
        String date = s1.format(curr_date);
        try
        {            
            Connection con=new Connect().connect();
            PreparedStatement p=con.prepareStatement("select * from payment where id=? and txn_no=?");
            p.setString(1,get_id);
            p.setString(2,txn_id);
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                full_name=rs.getString("name");
                id=rs.getString("id");
                course=rs.getString("course");
                amount=rs.getString("amount");
                upi_id=rs.getString("upi");
                card_no=rs.getString("card_no");
                expiry_date=rs.getString("expiry_date");
                card_holder_name=rs.getString("holder_name");
                txn_date=rs.getString("txn_date");
            }
            System.out.println(full_name+"\t"+id+"\t"+course+"\t"+amount+"\t"+upi_id+"\t"+card_no+"\t"+expiry_date+"\t"+card_holder_name);
            JFileChooser j=new JFileChooser();
            j.showSaveDialog(rootPane);
            File f=j.getSelectedFile();
            String path=f.getAbsolutePath();
            
            Document d=new Document();
            PdfWriter.getInstance(d, new FileOutputStream(path));
            d.open();
            if(upi_id.equals("-"))
            {
                               d.add(new Paragraph("                                               INDIAN INSTITUTE OF TECHNOLOGY" +
                        "\n                                                     HAUZ KHAS, NEW DELHI-110016"+
                        "\nDATE :- "+date+
                        "\n____________________________________________________________________________"+
                        "\n                                                     STUDENT INFORMATION"+
                        "\n____________________________________________________________________________"+
                        "\n"+                        
                        "Student-id :- "+id+"\n"+
                        "Student Name :- "+full_name+
                        "\nCourse :- "+course +                        
                        "\n____________________________________________________________________________"+
                        "\n                                                     PAYMENT INFORMATION"+
                        "\n____________________________________________________________________________"+
                        "\nPayment Method :- " +"Debit Card/Credit Card"+
                        "\nCard Number :- "+card_no+
                        "\nCard Holder Name :- "+card_holder_name+
                        "\nExpiry Number:-   "+expiry_date+
                        "\n\nTransaction Id :- "+txn_id+                        
                        "\nTransaction Date :- "+txn_date+
                        "\nAmount :- "+amount+   
                        
                        "\n\n\n\n\n\n\n\n\nNote:-\n     *This is the system generated reciept.There is no need of signature and stamp. "
                        
                ));
            }
            else
            {
               d.add(new Paragraph("                                               INDIAN INSTITUTE OF TECHNOLOGY" +
                        "\n                                                     HAUZ KHAS, NEW DELHI-110016"+
                        "\nDATE:-  "+date+
                        "\n____________________________________________________________________________"+
                        "\n                                                     STUDENT INFORMATION"+
                        "\n____________________________________________________________________________"+
                        "\n"+                        
                        "Student-id:- "+id+"\n"+
                        "Student Name:- "+full_name+
                        "\nCourse :-   "+course +
                        "\nSemester:-   " +                        
                        "\n____________________________________________________________________________"+
                        "\n                                                     PAYEMENT INFORMATION"+
                        "\n____________________________________________________________________________"+
                        "\nPayment Method :- "+"UPI \n"+                        
                        "UPI ID :- "+upi_id+"\n"+
                        "Transaction-id :- "+txn_id+"\n"+
                        "Transaction Date :- "+txn_date+"\n"+
                        "Amount :- "+amount+   
                        "\n\n\n\n\n\n\n\n\nNote:-\n     *This is the system generated reciept.There is no need of signature and stamp. "));
            }
            d.close();
            int i=JOptionPane.showConfirmDialog(rootPane,"Do you want to open this pdf?");
            if(i==0)
            {
                try
                {
                    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+f.getAbsolutePath());
                    this.dispose();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Your file has been downloaded.");
                this.dispose();
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees_reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees_reciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
