
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prince Giri
 */
public class students_report extends javax.swing.JInternalFrame {

    /**
     * Creates new form students_report
     */
    public students_report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT REPORT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("COURSE");

        jComboBox1.setForeground(new java.awt.Color(150, 150, 150));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------SELECT-------------------", "BCA", "BBA", "BJMC", "BCOM" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("SEMESTER");

        jComboBox2.setForeground(new java.awt.Color(150, 150, 150));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------SEMESTER--------------------", "I", "II", "III", "IV", "V", "VI", "-------------------YEAR-----------------------", "1ST", "2ND", "3RD", " " }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SHOW REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("SUB1");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("SUB2");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("SUB3");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("SUB4");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("SUB5");

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "COURSE", "SEMESTER", "SUB1", "SUB2", "SUB3", "SUB4", "SUB5", "TOTAL MARKS", "PERCENTAGE", "RESULT"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Download as PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, 0, 234, Short.MAX_VALUE))))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))))
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void show_details()
    {
        String course=(String)jComboBox1.getSelectedItem();
        String sem=(String)jComboBox2.getSelectedItem();
        
        Connect c=new Connect();
        
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=c.connect();
            PreparedStatement p=con.prepareStatement("select * from result_upload where course=? and sem=?;");
            p.setString(1,course);
            p.setString(2,sem);
            ResultSet rs=p.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        show_details();
        String course = (String)jComboBox1.getSelectedItem();
        String semester= (String)jComboBox2.getSelectedItem();
        if(course.equalsIgnoreCase("BCA") && semester.equals("I"))
        {
            jLabel13.setText("MATHS 1");
            jLabel11.setText("PROGRAMMING PRINCIPLES ");
            jLabel12.setText("COMPUTER FUNDAMENTALS");
            jLabel10.setText("PRINCIPLE OF MANAGEMENT");
            jLabel5.setText("BUSINESS MANAGEMENT");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equalsIgnoreCase("BCA") && semester.equals("II"))
        {
            jLabel13.setText("MATHS 2");
            jLabel11.setText("C PROGRAMMING");
            jLabel12.setText("ORGANISATIONAL BEHAVIOUR");
            jLabel10.setText("DIGITAL ELCTRONICS");
            jLabel5.setText("FUNDAMENTAL ACCOUNTING");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equalsIgnoreCase("BCA") && semester.equals("III"))
        {
            jLabel13.setText("OOPS CONCEPT");
            jLabel11.setText("DATA STRUCTURES");
            jLabel12.setText("COMPUTER ARCHITECTURE");
            jLabel10.setText("BUSINESS ECONOMICS");
            jLabel5.setText("STATISTICS");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equalsIgnoreCase("BCA") && semester.equals("IV"))
        {
            jLabel13.setText("CGMA");
            jLabel11.setText("OS");
            jLabel12.setText("SE");
            jLabel10.setText("OT");
            jLabel5.setText("MATHS 3");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equalsIgnoreCase("BCA") && semester.equals("V"))
        {
            jLabel13.setText("DBMS");
            jLabel11.setText("JAVA");
            jLabel12.setText("NETWORKING");
            jLabel10.setText("NUMERICAL METHODS");
            jLabel5.setText("MINOR PROJECT");
            jLabel9.hide();            
        }

        if(course.equalsIgnoreCase("BCA") && semester.equals("VI"))
        {
            jLabel13.setText("NETWORK SECURITY");
            jLabel11.setText("INFORMATION SYSTEM");
            jLabel12.setText("E-COMMERCE");
            jLabel10.setText("KNOWLEDGE MANAGEMENT");
            jLabel9.hide();
            jLabel5.hide();
        }

        if(course.equalsIgnoreCase("BBA") && semester.equals("I"))
        {
            jLabel13.setText("BUSINESS ORGANISATION");
            jLabel11.setText("BUSINESS MATHEMATICS");
            jLabel12.setText("BOOK KEEPING AND ACCOUNTING");
            jLabel10.setText("BUSINESS LAWS");
            jLabel5.setText("FUNDAMENTAL OF MANAGEMENT");
            jLabel5.show();
            jLabel9.show();
        }

        if(course.equalsIgnoreCase("BBA") && semester.equals("II"))
        {
            jLabel13.setText("OB");
            jLabel11.setText("BC");
            jLabel12.setText("INDIAN ECONMY");
            jLabel10.setText("BUSINESS STATISTICS");
            jLabel5.setText("BUSINESS ENVIRONMENT");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BBA") && semester.equals("III"))
        {
            jLabel13.setText("ADVERTISING MANAGEMENT");
            jLabel11.setText("INDIaN BANKING SYSTEM");
            jLabel12.setText("HR MANAGEMENT");
            jLabel10.setText("MARKETING MANAGEMENT");
            jLabel5.setText("ACCOUNTS");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BBA") && semester.equals("IV"))
        {
            jLabel13.setText("CONSUMER BEHAVIOUR");
            jLabel11.setText("FINANCIAL MANAGEMENT");
            jLabel12.setText("PRODUCTION MANAGEMENT");
            jLabel10.setText("SALES MANAGEMENT");
            jLabel5.setText("RESEARCH METHODOLOGY ");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BBA") && semester.equals("V"))
        {
            jLabel13.setText("MANAGERIAL ECONOMICS");
            jLabel11.setText("BUSINESS MANAGEMENT");
            jLabel12.setText("INCOME TAX");
            jLabel10.setText("COST & MANAGEMENT ACCOUNTING");
            jLabel5.setText("INDUSTRIAL LAW");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BBA") && semester.equals("VI"))
        {
            jLabel13.setText("INTERNATIONAL TRADE");
            jLabel11.setText("STRETAGIC MANAGEMENT");
            jLabel12.setText("VAT & SERVICE TAX");
            jLabel10.setText("MANAGEMENT INFORMATION SYSTEM");
            jLabel5.setText("AUDITING");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("I"))
        {
            jLabel13.setText("MASS COMMUNICATION");
            jLabel11.setText("COMPUTER BASICS");
            jLabel12.setText("VALUE EDUCATION");
            jLabel10.setText("GENERAL HINDI");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("II"))
        {
            jLabel13.setText("INTRO. TO JOURNALISM");
            jLabel11.setText("INDIAN POLITICAL SYSTEM");
            jLabel12.setText("INDAIN SOCIAL SYSTEM");
            jLabel10.setText("GENERAL ENGLISH");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("III"))
        {
            jLabel13.setText("PRINT MEDIA I");
            jLabel11.setText("INDIAN ECONOMIC SYSTEM");
            jLabel12.setText("ELECTRONIC MEDIA I");
            jLabel10.setText("MEDIA LAWS");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("IV"))
        {
            jLabel13.setText("PRINT MEDIA II");
            jLabel11.setText("SOCIAL MEDIA");
            jLabel12.setText("PUBLIC RELATIONS");
            jLabel10.setText("ELCTRONIC MEDIA II");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("V"))
        {
            jLabel13.setText("ADVERTISING");
            jLabel11.setText("DEVELOPMENT COMMUNICATION");
            jLabel12.setText("MASS MEDIA WRITING SKILLS");
            jLabel10.setText("DIGITAL JOURNALISM");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BJMC") && semester.equals("VI"))
        {
            jLabel13.setText("PRACTICAL-VIVA (PRINT MEDIA)");
            jLabel11.setText("PRACTICAL-VIVA (RADIO)");
            jLabel12.setText("PRACTICAL-VIVA (TV)");
            jLabel10.setText("PRACTICAL-VIVA (NEW MEDIA)");
            jLabel5.setText("VIVA");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BCOM") && semester.equals("1ST"))
        {
            jLabel13.setText("BUSINESS COMMUNICATION");
            jLabel11.setText("BUSINESS STATISTICS");
            jLabel12.setText("FINANCIAL ACCOUNTING");
            jLabel10.setText("REGULATORY FRAMEWORK");
            jLabel5.setText("BUSINESS ECONIMICS");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BCOM") && semester.equals("2ND"))
        {
            jLabel13.setText("COMPANY LAW");
            jLabel11.setText("COST ACCOUNTING");
            jLabel12.setText("BUSINESS MANAGEMENT");
            jLabel10.setText("INCOME TAX");
            jLabel5.setText("INTRO. TO ENTREPRENEURSHIP");
            jLabel9.show();
            jLabel5.show();
        }

        if(course.equals("BCOM") && semester.equals("3RD"))
        {
            jLabel13.setText("CORPORATE ACCOUNTING");
            jLabel11.setText("AUDITING");
            jLabel12.setText("PRINCIPLE OF MARKETING");
            jLabel10.setText("ECONOMICS LAWS");
            jLabel5.setText("MANAGEMENT ACCOUNTING");
            jLabel9.show();
            jLabel5.show();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ResultDownload rd=new ResultDownload(jLabel13.getText(),jLabel11.getText(),jLabel12.getText(),jLabel10.getText(),jLabel5.getText());
        rd.setVisible(true);
        rd.toFront();
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
